# filepath: d:\Dev\ACS\acs-frontend\.github\workflows\deploy.yml
name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connexion SSH et déploiement du Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -f /var/www/deploy-frontend.sh ]; then
              chmod +x /var/www/deploy-frontend.sh
              /var/www/deploy-frontend.sh
            else
              echo "File /var/www/deploy-frontend.sh not found"
              exit 1
            fi
